from typing import Any
import shutil
import sys
from pathlib import Path


def write_smoke_loop_vcd(output_dir: Any) -> Any:
    smoke_dir = Path(output_dir) / "smoke-loop"
    smoke_dir.mkdir(parents=True, exist_ok=True)
    vcd_path = smoke_dir / "handshake_trace.vcd"
    vcd_path.write_text(
        """$date
    Generated by DigitalICAgent smoke loop
$end
$version
    DigitalICAgent built-in handshake smoke loop
$end
$timescale 1ns $end
$scope module tb $end
$var wire 1 ! clk $end
$var wire 1 " valid $end
$var wire 1 # ready $end
$var wire 8 $ data $end
$upscope $end
$enddefinitions $end
#0
0!
0"
0#
b00000000 $
#5
1!
#10
1"
1#
b10101010 $
#15
0"
#20
1"
b01010101 $
#25
0"
#30
0#
0!
""",
        encoding="utf-8",
    )
    return vcd_path


def run_smoke_loop(
    agent: Any,
    output_dir: Any="outputs",
    limit: Any=20,
    waveform_backend: Any="auto",
) -> Any:
    print("Smoke loop: generating built-in handshake VCD")
    vcd_path = agent.write_smoke_loop_vcd(output_dir)
    print("Generated VCD: {}".format(vcd_path))
    ok = agent.analyze_vcd(
        vcd_path,
        condition="tb.valid=1,tb.ready=1",
        show="tb.data",
        limit=limit,
        waveform_backend=waveform_backend,
    )
    if ok:
        print("Smoke loop completed")
    return ok


def detect_simulator(agent: Any) -> Any:
    if agent.resolve_vivado_command():
        return "vivado"
    if shutil.which("iverilog") and shutil.which("vvp"):
        return "icarus"
    if shutil.which("verilator"):
        return "verilator"
    return None


def write_sim_smoke_sources(output_dir: Any) -> Any:
    sim_dir = Path(output_dir) / "sim-smoke"
    sim_dir.mkdir(parents=True, exist_ok=True)

    rtl_path = sim_dir / "handshake_passthrough.v"
    tb_path = sim_dir / "tb_handshake.v"
    vcd_path = sim_dir / "handshake_trace.vcd"

    rtl_path.write_text(
        """`timescale 1ns/1ps

module handshake_passthrough (
    input wire clk,
    input wire rst_n,
    input wire valid,
    input wire ready,
    input wire [7:0] data_in,
    output wire [7:0] data
);
    assign data = data_in;
endmodule
""",
        encoding="utf-8",
    )

    tb_path.write_text(
        """`timescale 1ns/1ps

module tb;
    reg clk;
    reg rst_n;
    reg valid;
    reg ready;
    reg [7:0] data_in;
    wire [7:0] data;

    handshake_passthrough dut (
        .clk(clk),
        .rst_n(rst_n),
        .valid(valid),
        .ready(ready),
        .data_in(data_in),
        .data(data)
    );

    initial begin
        clk = 1'b0;
        forever #5 clk = ~clk;
    end

    initial begin
        $dumpfile("handshake_trace.vcd");
        $dumpvars(0, tb);

        rst_n = 1'b0;
        valid = 1'b0;
        ready = 1'b0;
        data_in = 8'h00;

        #10;
        rst_n = 1'b1;
        valid = 1'b1;
        ready = 1'b1;
        data_in = 8'haa;

        #5;
        valid = 1'b0;

        #5;
        valid = 1'b1;
        data_in = 8'h55;

        #5;
        valid = 1'b0;

        #5;
        ready = 1'b0;
        #5;
        $finish;
    end
endmodule
""",
        encoding="utf-8",
    )

    return sim_dir, rtl_path, tb_path, vcd_path


def run_icarus_sim_smoke(
    agent: Any,
    output_dir: Any,
    limit: Any=20,
    waveform_backend: Any="auto",
) -> Any:
    sim_dir, rtl_path, tb_path, vcd_path = agent.write_sim_smoke_sources(output_dir)
    sim_out = sim_dir / "handshake_smoke.vvp"

    compile_result = agent.command_runner.run(
        ["iverilog", "-g2012", "-o", sim_out, rtl_path, tb_path],
        cwd=sim_dir,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )
    if compile_result.returncode != 0:
        print(compile_result.stderr.strip() or "iverilog compile failed", file=sys.stderr)
        return False

    run_result = agent.command_runner.run(
        ["vvp", sim_out],
        cwd=sim_dir,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )
    if run_result.returncode != 0:
        print(run_result.stderr.strip() or "vvp simulation failed", file=sys.stderr)
        return False

    if not vcd_path.exists():
        print("Simulation did not generate VCD: {}".format(vcd_path), file=sys.stderr)
        return False

    print("Simulator: icarus")
    print("Generated VCD: {}".format(vcd_path))
    ok = agent.analyze_vcd(
        vcd_path,
        condition="tb.valid=1,tb.ready=1",
        show="tb.data",
        limit=limit,
        waveform_backend=waveform_backend,
    )
    if ok:
        print("Simulation smoke completed")
    return ok


def write_vivado_sim_script(sim_dir: Any, rtl_path: Any, tb_path: Any, vcd_path: Any) -> Any:
    script_path = Path(sim_dir) / "run_vivado_sim.tcl"
    script_path.write_text(
        """set script_dir [file dirname [file normalize [info script]]]
cd $script_dir
file delete -force xsim.dir .Xil xvlog.pb xelab.pb xsim.jou xsim.log xvlog.log
exec xvlog -sv handshake_passthrough.v tb_handshake.v
exec xelab tb -debug typical -s handshake_smoke
exec xsim handshake_smoke -R
if {![file exists handshake_trace.vcd]} {
    puts stderr "Simulation did not generate handshake_trace.vcd"
    exit 1
}
exit 0
""",
        encoding="utf-8",
    )
    return script_path


def open_vivado_wave_gui(agent: Any, sim_dir: Any, vcd_path: Any) -> Any:
    wave_db_path = Path(sim_dir) / "handshake_smoke.wdb"
    gui_script_path = Path(sim_dir) / "open_vivado_wave.tcl"
    gui_script_path.write_text(
        """set script_dir [file dirname [file normalize [info script]]]
cd $script_dir
set wave_db handshake_smoke.wdb
if {![file exists $wave_db]} {
    puts stderr "Waveform database not found: $wave_db"
    exit 1
}
start_gui
open_wave_database $wave_db
add_wave -r /*
""",
        encoding="utf-8",
    )

    if not wave_db_path.exists():
        print("Vivado waveform database not found: {}".format(wave_db_path), file=sys.stderr)
        return False

    vivado_command = agent.resolve_vivado_command()
    if not vivado_command:
        print("Vivado command not found; cannot open waveform GUI.", file=sys.stderr)
        return False

    agent.launch_vivado_gui(vivado_command, gui_script_path.name, sim_dir)
    print("Vivado waveform GUI launched: {}".format(wave_db_path))
    return True


def run_vivado_sim_smoke(
    agent: Any,
    output_dir: Any,
    limit: Any=20,
    open_wave_gui: Any=True,
    waveform_backend: Any="auto",
) -> Any:
    sim_dir, rtl_path, tb_path, vcd_path = agent.write_sim_smoke_sources(output_dir)
    script_path = agent.write_vivado_sim_script(sim_dir, rtl_path, tb_path, vcd_path)
    vivado_command = agent.resolve_vivado_command()
    if not vivado_command:
        print("Vivado command not found.", file=sys.stderr)
        return False

    result = agent.run_vivado_batch(
        vivado_command,
        script_path.name,
        sim_dir,
    )
    if result.returncode != 0:
        print(
            result.stderr.strip() or result.stdout.strip() or "vivado simulation failed",
            file=sys.stderr,
        )
        return False

    if not vcd_path.exists():
        print("Simulation did not generate VCD: {}".format(vcd_path), file=sys.stderr)
        return False

    print("Simulator: vivado")
    print("Generated VCD: {}".format(vcd_path))
    ok = agent.analyze_vcd(
        vcd_path,
        condition="tb.valid=1,tb.ready=1",
        show="tb.data",
        limit=limit,
        waveform_backend=waveform_backend,
    )
    if ok:
        print("Simulation smoke completed")
        if open_wave_gui:
            agent.open_vivado_wave_gui(sim_dir, vcd_path)
    return ok


def run_sim_smoke(
    agent: Any,
    output_dir: Any="outputs",
    limit: Any=20,
    open_wave_gui: Any=True,
    waveform_backend: Any="auto",
) -> Any:
    simulator = agent.detect_simulator()
    if simulator is None:
        print(
            "No supported Verilog simulator found. Install iverilog/vvp, verilator, or vivado; "
            "use --smoke-loop for the built-in VCD fallback.",
            file=sys.stderr,
        )
        return False
    if simulator == "vivado":
        return agent.run_vivado_sim_smoke(
            output_dir=output_dir,
            limit=limit,
            open_wave_gui=open_wave_gui,
            waveform_backend=waveform_backend,
        )
    if simulator == "icarus":
        return agent.run_icarus_sim_smoke(
            output_dir=output_dir,
            limit=limit,
            waveform_backend=waveform_backend,
        )

    print(
        "{} detected, but sim smoke currently supports only Vivado or iverilog/vvp.".format(
            simulator
        ),
        file=sys.stderr,
    )
    return False


def render_vivado_tclstore_bootstrap() -> Any:
    return """proc source_pkg_index {index_file} {
    if {[file exists $index_file]} {
        set old_dir_exists [info exists ::dir]
        if {$old_dir_exists} {
            set old_dir $::dir
        }
        set ::dir [file dirname $index_file]
        uplevel #0 [list source $index_file]
        if {$old_dir_exists} {
            set ::dir $old_dir
        } else {
            unset -nocomplain ::dir
        }
    }
}

set vivado_exe [file normalize [info nameofexecutable]]
set vivado_root [file dirname [file dirname [file dirname [file dirname $vivado_exe]]]]
set install_store [file join $vivado_root data XilinxTclStore]
if {![file isdirectory $install_store]} {
    set install_store [file normalize "D:/vivado/2025.2/Vivado/data/XilinxTclStore"]
}
set support_dir [file join $install_store support]
set appinit_dir [file join $support_dir appinit]
set tclapp_dir [file join $install_store tclapp]
set xilinx_dir [file join $tclapp_dir xilinx]
set xsim_dir [file join $xilinx_dir xsim]
foreach dir_path [list $support_dir $appinit_dir $tclapp_dir $xilinx_dir $xsim_dir] {
    if {[file isdirectory $dir_path] && [lsearch -exact $::auto_path $dir_path] == -1} {
        lappend ::auto_path $dir_path
    }
}
foreach index_file [list \
    [file join $support_dir pkgIndex.tcl] \
    [file join $appinit_dir pkgIndex.tcl] \
    [file join $tclapp_dir pkgIndex.tcl] \
    [file join $xilinx_dir pkgIndex.tcl] \
    [file join $xsim_dir pkgIndex.tcl] \
] {
    source_pkg_index $index_file
}
catch {package require ::tclapp::support::appinit 1.2}
catch {package require ::tclapp::xilinx::xsim 2.520}
"""
