from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TESTS_DIR = ROOT / "tests"
DEFAULT_LINE_LIMIT = 1000


def count_lines(path: Path) -> int:
    return len(path.read_text(encoding="utf-8").splitlines())


def collect_test_function_names(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    return [
        node.name
        for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
        and node.name.startswith("test_")
    ]


def summarize_test_modules(tests_dir: Path, line_limit: int) -> dict[str, Any]:
    resolved_root = ROOT.resolve()
    resolved_tests_dir = tests_dir.resolve()
    repo_tests_dir = DEFAULT_TESTS_DIR.resolve()
    modules: list[dict[str, Any]] = []
    module_paths: dict[str, Path] = {}

    for path in sorted(resolved_tests_dir.glob("test_*.py")):
        line_count = count_lines(path)
        if resolved_tests_dir == repo_tests_dir:
            relative_path = path.relative_to(resolved_root).as_posix()
        else:
            relative_path = path.relative_to(resolved_tests_dir).as_posix()
        modules.append(
            {
                "path": relative_path,
                "lines": line_count,
                "status": "OVER_LIMIT" if line_count > line_limit else "OK",
            }
        )
        module_paths[relative_path] = path

    over_limit = [module for module in modules if module["status"] == "OVER_LIMIT"]
    unmigrated_tests = []
    for module in over_limit:
        source = str(module["path"])
        test_names = collect_test_function_names(module_paths[source])
        if test_names:
            unmigrated_tests.append({"source": source, "tests": test_names})

    return {
        "schema_version": 1,
        "line_limit": line_limit,
        "module_count": len(modules),
        "over_limit_count": len(over_limit),
        "modules": modules,
        "split_candidates": [],
        "deletion_verification": [],
        "unmigrated_tests": unmigrated_tests,
        "unfinished_items": [
            {
                "path": module["path"],
                "lines": module["lines"],
                "reason": "test module exceeds P2 line limit",
            }
            for module in over_limit
        ],
        "status": "PASS" if not over_limit else "WARN",
    }


def render_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# Test Module Size Report",
        "",
        "Generated by `python scripts/generate_test_module_report.py`.",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
        f"| Test modules | {summary['module_count']} |",
        f"| Line limit | {summary['line_limit']} |",
        f"| Over-limit modules | {summary['over_limit_count']} |",
        "",
        "| Module | Lines | Status |",
        "| --- | ---: | --- |",
    ]
    for module in sorted(
        summary["modules"],
        key=lambda item: (-int(item["lines"]), str(item["path"])),
    ):
        lines.append(f"| `{module['path']}` | {module['lines']} | {module['status']} |")

    lines.extend(["", "## Unfinished Items", ""])
    if summary["unfinished_items"]:
        for item in summary["unfinished_items"]:
            lines.append(
                "- `{}`: {} lines; {}".format(
                    item["path"],
                    item["lines"],
                    item["reason"],
                )
            )
    else:
        lines.append("- None.")

    lines.extend(["", "## Unmigrated Tests", ""])
    if summary["unmigrated_tests"]:
        for item in summary["unmigrated_tests"]:
            lines.append(
                "- `{}`: {}".format(
                    item["source"],
                    ", ".join(f"`{name}`" for name in item["tests"]),
                )
            )
    else:
        lines.append("- None.")

    lines.extend(["", "## Split Candidates", "", "- None."])
    lines.extend(["", "## Deletion Verification", "", "- None."])
    lines.extend(["", f"Status: `{summary['status']}`", ""])
    return "\n".join(lines)


def write_report(output_dir: Path, summary: dict[str, Any]) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "test_module_report.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (output_dir / "test_module_report.md").write_text(
        render_markdown(summary),
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate test module size report.")
    parser.add_argument("--tests-dir", type=Path, default=DEFAULT_TESTS_DIR)
    parser.add_argument("--line-limit", type=int, default=DEFAULT_LINE_LIMIT)
    parser.add_argument("--output-dir", type=Path, default=ROOT / "docs" / "generated")
    args = parser.parse_args()

    summary = summarize_test_modules(args.tests_dir, args.line_limit)
    write_report(args.output_dir, summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
