import shutil
import sys
from pathlib import Path
from collections.abc import Sequence
from typing import Protocol, TextIO


class CompletedProcessLike(Protocol):
    returncode: int
    stdout: str
    stderr: str


class CommandRunnerLike(Protocol):
    def run(
        self,
        command: Sequence[str | Path],
        **kwargs: object,
    ) -> CompletedProcessLike:
        ...


class SimulatorDetector(Protocol):
    def resolve_vivado_command(self) -> str | None:
        ...


class SmokeLoopAgent(Protocol):
    def write_smoke_loop_vcd(self, output_dir: str | Path) -> Path:
        ...

    def analyze_vcd(
        self,
        vcd_path: str | Path,
        condition: str | None = None,
        show: str | None = None,
        limit: int = 20,
        waveform_backend: str = "auto",
    ) -> bool:
        ...


class IcarusSmokeAgent(SmokeLoopAgent, Protocol):
    @property
    def command_runner(self) -> CommandRunnerLike:
        ...

    def write_sim_smoke_sources(self, output_dir: str | Path) -> tuple[Path, Path, Path, Path]:
        ...


class VivadoGuiAgent(SimulatorDetector, Protocol):
    def launch_vivado_gui(
        self,
        vivado_command: str,
        script_name: str,
        working_dir: str | Path,
    ) -> object:
        ...


class VivadoSmokeAgent(SmokeLoopAgent, VivadoGuiAgent, Protocol):
    def write_sim_smoke_sources(self, output_dir: str | Path) -> tuple[Path, Path, Path, Path]:
        ...

    def write_vivado_sim_script(
        self,
        sim_dir: str | Path,
        rtl_path: str | Path,
        tb_path: str | Path,
        vcd_path: str | Path,
    ) -> Path:
        ...

    def run_vivado_batch(
        self,
        vivado_command: str,
        script_name: str,
        working_dir: str | Path,
    ) -> CompletedProcessLike:
        ...

    def open_vivado_wave_gui(self, sim_dir: str | Path, vcd_path: str | Path) -> bool:
        ...


class SimSmokeAgent(IcarusSmokeAgent, VivadoSmokeAgent, Protocol):
    def detect_simulator(self) -> str | None:
        ...

    def run_vivado_sim_smoke(
        self,
        output_dir: str | Path,
        limit: int = 20,
        open_wave_gui: bool = True,
        waveform_backend: str = "auto",
    ) -> bool:
        ...

    def run_icarus_sim_smoke(
        self,
        output_dir: str | Path,
        limit: int = 20,
        waveform_backend: str = "auto",
    ) -> bool:
        ...


def emit_lines(lines: list[str], stream: TextIO | None = None) -> None:
    target_stream = stream or sys.stdout
    for line in lines:
        print(line, file=target_stream)


def build_smoke_loop_start_lines() -> list[str]:
    return ["Smoke loop: generating built-in handshake VCD"]


def build_generated_vcd_lines(vcd_path: str | Path) -> list[str]:
    return ["Generated VCD: {}".format(vcd_path)]


def build_sim_smoke_completed_lines() -> list[str]:
    return ["Simulation smoke completed"]


def build_sim_smoke_success_lines(simulator: str, vcd_path: str | Path) -> list[str]:
    return [
        "Simulator: {}".format(simulator),
        *build_generated_vcd_lines(vcd_path),
    ]


def build_sim_smoke_error_lines(message: str) -> list[str]:
    return [message]


def write_smoke_loop_vcd(output_dir: str | Path) -> Path:
    smoke_dir = Path(output_dir) / "smoke-loop"
    smoke_dir.mkdir(parents=True, exist_ok=True)
    vcd_path = smoke_dir / "handshake_trace.vcd"
    vcd_path.write_text(
        """$date
    Generated by DigitalICAgent smoke loop
$end
$version
    DigitalICAgent built-in handshake smoke loop
$end
$timescale 1ns $end
$scope module tb $end
$var wire 1 ! clk $end
$var wire 1 " valid $end
$var wire 1 # ready $end
$var wire 8 $ data $end
$upscope $end
$enddefinitions $end
#0
0!
0"
0#
b00000000 $
#5
1!
#10
1"
1#
b10101010 $
#15
0"
#20
1"
b01010101 $
#25
0"
#30
0#
0!
""",
        encoding="utf-8",
    )
    return vcd_path


def run_smoke_loop(
    agent: SmokeLoopAgent,
    output_dir: str | Path = "outputs",
    limit: int = 20,
    waveform_backend: str = "auto",
) -> bool:
    emit_lines(build_smoke_loop_start_lines())
    vcd_path = agent.write_smoke_loop_vcd(output_dir)
    emit_lines(build_generated_vcd_lines(vcd_path))
    ok = agent.analyze_vcd(
        vcd_path,
        condition="tb.valid=1,tb.ready=1",
        show="tb.data",
        limit=limit,
        waveform_backend=waveform_backend,
    )
    if ok:
        emit_lines(["Smoke loop completed"])
    return ok


def detect_simulator(agent: SimulatorDetector) -> str | None:
    if agent.resolve_vivado_command():
        return "vivado"
    if shutil.which("iverilog") and shutil.which("vvp"):
        return "icarus"
    if shutil.which("verilator"):
        return "verilator"
    return None


def write_sim_smoke_sources(output_dir: str | Path) -> tuple[Path, Path, Path, Path]:
    sim_dir = Path(output_dir) / "sim-smoke"
    sim_dir.mkdir(parents=True, exist_ok=True)

    rtl_path = sim_dir / "handshake_passthrough.v"
    tb_path = sim_dir / "tb_handshake.v"
    vcd_path = sim_dir / "handshake_trace.vcd"

    rtl_path.write_text(
        """`timescale 1ns/1ps

module handshake_passthrough (
    input wire clk,
    input wire rst_n,
    input wire valid,
    input wire ready,
    input wire [7:0] data_in,
    output wire [7:0] data
);
    assign data = data_in;
endmodule
""",
        encoding="utf-8",
    )

    tb_path.write_text(
        """`timescale 1ns/1ps

module tb;
    reg clk;
    reg rst_n;
    reg valid;
    reg ready;
    reg [7:0] data_in;
    wire [7:0] data;

    handshake_passthrough dut (
        .clk(clk),
        .rst_n(rst_n),
        .valid(valid),
        .ready(ready),
        .data_in(data_in),
        .data(data)
    );

    initial begin
        clk = 1'b0;
        forever #5 clk = ~clk;
    end

    initial begin
        $dumpfile("handshake_trace.vcd");
        $dumpvars(0, tb);

        rst_n = 1'b0;
        valid = 1'b0;
        ready = 1'b0;
        data_in = 8'h00;

        #10;
        rst_n = 1'b1;
        valid = 1'b1;
        ready = 1'b1;
        data_in = 8'haa;

        #5;
        valid = 1'b0;

        #5;
        valid = 1'b1;
        data_in = 8'h55;

        #5;
        valid = 1'b0;

        #5;
        ready = 1'b0;
        #5;
        $finish;
    end
endmodule
""",
        encoding="utf-8",
    )

    return sim_dir, rtl_path, tb_path, vcd_path


def run_icarus_sim_smoke(
    agent: IcarusSmokeAgent,
    output_dir: str | Path,
    limit: int = 20,
    waveform_backend: str = "auto",
) -> bool:
    sim_dir, rtl_path, tb_path, vcd_path = agent.write_sim_smoke_sources(output_dir)
    sim_out = sim_dir / "handshake_smoke.vvp"

    compile_result = agent.command_runner.run(
        ["iverilog", "-g2012", "-o", sim_out, rtl_path, tb_path],
        cwd=sim_dir,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )
    if compile_result.returncode != 0:
        emit_lines(
            build_sim_smoke_error_lines(
                compile_result.stderr.strip() or "iverilog compile failed"
            ),
            stream=sys.stderr,
        )
        return False

    run_result = agent.command_runner.run(
        ["vvp", sim_out],
        cwd=sim_dir,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )
    if run_result.returncode != 0:
        emit_lines(
            build_sim_smoke_error_lines(run_result.stderr.strip() or "vvp simulation failed"),
            stream=sys.stderr,
        )
        return False

    if not vcd_path.exists():
        emit_lines(
            build_sim_smoke_error_lines("Simulation did not generate VCD: {}".format(vcd_path)),
            stream=sys.stderr,
        )
        return False

    emit_lines(build_sim_smoke_success_lines("icarus", vcd_path))
    ok = agent.analyze_vcd(
        vcd_path,
        condition="tb.valid=1,tb.ready=1",
        show="tb.data",
        limit=limit,
        waveform_backend=waveform_backend,
    )
    if ok:
        emit_lines(build_sim_smoke_completed_lines())
    return ok


def write_vivado_sim_script(
    sim_dir: str | Path,
    rtl_path: str | Path,
    tb_path: str | Path,
    vcd_path: str | Path,
) -> Path:
    script_path = Path(sim_dir) / "run_vivado_sim.tcl"
    script_path.write_text(
        """set script_dir [file dirname [file normalize [info script]]]
cd $script_dir
file delete -force xsim.dir .Xil xvlog.pb xelab.pb xsim.jou xsim.log xvlog.log
exec xvlog -sv handshake_passthrough.v tb_handshake.v
exec xelab tb -debug typical -s handshake_smoke
exec xsim handshake_smoke -R
if {![file exists handshake_trace.vcd]} {
    puts stderr "Simulation did not generate handshake_trace.vcd"
    exit 1
}
exit 0
""",
        encoding="utf-8",
    )
    return script_path


def open_vivado_wave_gui(
    agent: VivadoGuiAgent,
    sim_dir: str | Path,
    vcd_path: str | Path,
) -> bool:
    wave_db_path = Path(sim_dir) / "handshake_smoke.wdb"
    gui_script_path = Path(sim_dir) / "open_vivado_wave.tcl"
    gui_script_path.write_text(
        """set script_dir [file dirname [file normalize [info script]]]
cd $script_dir
set wave_db handshake_smoke.wdb
if {![file exists $wave_db]} {
    puts stderr "Waveform database not found: $wave_db"
    exit 1
}
start_gui
open_wave_database $wave_db
add_wave -r /*
""",
        encoding="utf-8",
    )

    if not wave_db_path.exists():
        emit_lines(
            build_sim_smoke_error_lines(
                "Vivado waveform database not found: {}".format(wave_db_path)
            ),
            stream=sys.stderr,
        )
        return False

    vivado_command = agent.resolve_vivado_command()
    if not vivado_command:
        emit_lines(
            build_sim_smoke_error_lines(
                "Vivado command not found; cannot open waveform GUI."
            ),
            stream=sys.stderr,
        )
        return False

    agent.launch_vivado_gui(vivado_command, gui_script_path.name, sim_dir)
    emit_lines(["Vivado waveform GUI launched: {}".format(wave_db_path)])
    return True


def run_vivado_sim_smoke(
    agent: VivadoSmokeAgent,
    output_dir: str | Path,
    limit: int = 20,
    open_wave_gui: bool = True,
    waveform_backend: str = "auto",
) -> bool:
    sim_dir, rtl_path, tb_path, vcd_path = agent.write_sim_smoke_sources(output_dir)
    script_path = agent.write_vivado_sim_script(sim_dir, rtl_path, tb_path, vcd_path)
    vivado_command = agent.resolve_vivado_command()
    if not vivado_command:
        emit_lines(
            build_sim_smoke_error_lines("Vivado command not found."),
            stream=sys.stderr,
        )
        return False

    result = agent.run_vivado_batch(
        vivado_command,
        script_path.name,
        sim_dir,
    )
    if result.returncode != 0:
        emit_lines(
            build_sim_smoke_error_lines(
                result.stderr.strip() or result.stdout.strip() or "vivado simulation failed"
            ),
            stream=sys.stderr,
        )
        return False

    if not vcd_path.exists():
        emit_lines(
            build_sim_smoke_error_lines("Simulation did not generate VCD: {}".format(vcd_path)),
            stream=sys.stderr,
        )
        return False

    emit_lines(build_sim_smoke_success_lines("vivado", vcd_path))
    ok = agent.analyze_vcd(
        vcd_path,
        condition="tb.valid=1,tb.ready=1",
        show="tb.data",
        limit=limit,
        waveform_backend=waveform_backend,
    )
    if ok:
        emit_lines(build_sim_smoke_completed_lines())
        if open_wave_gui:
            agent.open_vivado_wave_gui(sim_dir, vcd_path)
    return ok


def run_sim_smoke(
    agent: SimSmokeAgent,
    output_dir: str | Path = "outputs",
    limit: int = 20,
    open_wave_gui: bool = True,
    waveform_backend: str = "auto",
) -> bool:
    simulator = agent.detect_simulator()
    if simulator is None:
        emit_lines(
            build_sim_smoke_error_lines(
                "No supported Verilog simulator found. Install iverilog/vvp, verilator, or vivado; "
                "use --smoke-loop for the built-in VCD fallback."
            ),
            stream=sys.stderr,
        )
        return False
    if simulator == "vivado":
        return agent.run_vivado_sim_smoke(
            output_dir=output_dir,
            limit=limit,
            open_wave_gui=open_wave_gui,
            waveform_backend=waveform_backend,
        )
    if simulator == "icarus":
        return agent.run_icarus_sim_smoke(
            output_dir=output_dir,
            limit=limit,
            waveform_backend=waveform_backend,
        )

    emit_lines(
        build_sim_smoke_error_lines(
            "{} detected, but sim smoke currently supports only Vivado or iverilog/vvp.".format(
                simulator
            )
        ),
        stream=sys.stderr,
    )
    return False


def render_vivado_tclstore_bootstrap() -> str:
    return """proc source_pkg_index {index_file} {
    if {[file exists $index_file]} {
        set old_dir_exists [info exists ::dir]
        if {$old_dir_exists} {
            set old_dir $::dir
        }
        set ::dir [file dirname $index_file]
        uplevel #0 [list source $index_file]
        if {$old_dir_exists} {
            set ::dir $old_dir
        } else {
            unset -nocomplain ::dir
        }
    }
}

set vivado_exe [file normalize [info nameofexecutable]]
set vivado_root [file dirname [file dirname [file dirname [file dirname $vivado_exe]]]]
set install_store [file join $vivado_root data XilinxTclStore]
if {![file isdirectory $install_store]} {
    set install_store [file normalize "D:/vivado/2025.2/Vivado/data/XilinxTclStore"]
}
set support_dir [file join $install_store support]
set appinit_dir [file join $support_dir appinit]
set tclapp_dir [file join $install_store tclapp]
set xilinx_dir [file join $tclapp_dir xilinx]
set xsim_dir [file join $xilinx_dir xsim]
foreach dir_path [list $support_dir $appinit_dir $tclapp_dir $xilinx_dir $xsim_dir] {
    if {[file isdirectory $dir_path] && [lsearch -exact $::auto_path $dir_path] == -1} {
        lappend ::auto_path $dir_path
    }
}
foreach index_file [list \
    [file join $support_dir pkgIndex.tcl] \
    [file join $appinit_dir pkgIndex.tcl] \
    [file join $tclapp_dir pkgIndex.tcl] \
    [file join $xilinx_dir pkgIndex.tcl] \
    [file join $xsim_dir pkgIndex.tcl] \
] {
    source_pkg_index $index_file
}
catch {package require ::tclapp::support::appinit 1.2}
catch {package require ::tclapp::xilinx::xsim 2.520}
"""
